### ISSUE TITLE
Please add PCG

### ISSUE THREAD

**Issue by essen** [jj1bdx/emprng#10]
http://www.pcg-random.org/

And if the table is true, should probably be the default.

Cheers.

**Comment by jj1bdx** [comment]
@essen the code seems to be simple enough, and I see the code looks quite similar to XorShift*'s. I'll give it a try, probably studying it first and making it as an independent repository (as all the algorithms included here are), and then as a part of emprng. Thx for suggestion.

**Comment by essen** [comment]
Cool, keeps me posted, I am intrigued but nowhere knowledgeable enough to know whether the claims are correct.

**Comment by jj1bdx** [comment]
One criticism from Sebatiano Vigna against PCG. http://v8project.blogspot.jp/2015/12/theres-mathrandom-and-then-theres.html?showComment=1452592903162#c1549004517443909784

**Comment by jj1bdx** [comment]
According to the later development of PCG .vs. Xorshift*/+, I conclude, for the time being as of September 2016, that PCG will not be included in the "rand" module candidate, due to the following facts:
- Benchmarking of PCG by Sebastiano Vigna does not indicate PCG's substantial advantage against Xorshift*/+ (See http://xoroshiro.di.unimi.it/#quality)
- PCG's author has not publicly compare the results with exsplus (Xorshift116+) and exs1024 (Xorshift1024*) algorithms
- exs64 (Xorshift64*) has been phased out from Sebastiano Vigna's latest (as of September 2016) algorithm choice

Note:  the exs64 code will remain in the rand module to use it as the initialization function of generating longer seed from the given three-element integers (See https://github.com/jj1bdx/emprng/blob/0.5.0/src/rand.erl#L311L313 for the details)

**Comment by jj1bdx** [comment]
Issue closed for the time being; any further development of PCG may result in reopening the issue.

**Comment by essen** [comment]
Good enough reasons, thanks!
